import express from "express";
import userUpdate from "./routes/userUpdate";
import authentication from "./routes/authentication";
import userOTP from "./routes/userOTP";
import products from "./routes/products";
import userDetails from "./routes/userDetails";
import siteData from "./routes/siteData";
import productCheckout from "./routes/productCheckout";
import cartCheckout from "./routes/cartCheckout";
import homeData from "./routes/homeData";
import support from "./routes/support";
import adminRoutes from "./routes/admin";
import brandsRouter from "./routes/brands";
import collectionsRouter from "./routes/collections";
import productCatalog from "./routes/productCatalog";
import couponsRouter from './routes/coupons';
import warehouseRoutes from "./routes/warehouse";
import salesRoutes from "./routes/sales";
import toyFilter from "./routes/toyFilter";
import customerOrdersRoutes from "./routes/customerOrders";
import notificationsRoutes from "./routes/notifications";

const router = express.Router();

router.use("/", authentication);
router.use("/update", userUpdate);
router.use("/", userOTP);
router.use("/", products);
router.use("/", userDetails);
router.use("/", siteData);
router.use("/", productCheckout);
router.use("/", cartCheckout);
router.use("/", homeData);
router.use("/", support);
router.use("/", adminRoutes);
router.use("/brands", brandsRouter);
router.use("/collections", collectionsRouter);
router.use("/", productCatalog);
router.use("/", toyFilter);
router.use("/coupons", couponsRouter);
router.use("/warehouse", warehouseRoutes);
router.use("/sales", salesRoutes);
router.use("/", customerOrdersRoutes);
router.use("/", notificationsRoutes);
export default router;
